### ISSUE TITLE
could you make JsonLdTypeName annotation in field level as well?

### ISSUE THREAD

**Issue by mrtylmz** [Kobee1203/schema-org-java#84]
At the moment this annotation can be used type and annotation_type levels. could you also add the field level for this?
I want to change the name of the property on my use case.

I want to add this property into my dataset
prov:wasDerivedFrom

But in java, we cannot define the variable names using ":" character. So I need to have an annotation to override the variable name.

Thanks

**Comment by Kobee1203** [comment]
Could you give me more details?

- Do you generate your Java classes from a jsonld file and your field is defined in this file?
  - If so, could you provide me the JSONLD file so that I can see its content and how to handle it?
- Do you only use the serializer/deserializer from objects you already have?

I think the `JsonLdTypeName` annotation should not be used because it is only used to set and get the data type at the class level.

Moreover, it seems to me that you want to manage the PROV Data Model.
In this case, the generator should rather manage the PROV properties, and generate the field and the associated methods.

In your case, this would mean to have a generated class containing the `wasDerivedFrom` field (and not `prov:wasDerivedFrom`) and the associated getters and setters.
Tell me if I'm wrong about your need.

**Comment by mrtylmz** [comment]
I have my own DatasetImpl(MyDatasetImpl.java) class which is an extended class from DatasetImpl class. And there is a new variable in this class which is prov:wasDerivedFrom to support the dataset lineage feature because there is no property on scheme.org for this.
See below for my class
public class MyDatasetImpl extends DatasetImpl {
private DatasetImpl provWasDerivedFrom;
//getters and setters
}

after serialization, it creates provWasDerivedFrom property and it is not compatible with schema.org . 
So property name suppose to be prov:wasDerivedFrom to become fully compatible. Therefore I need to have JsonLdTypeName or similar annotation to rename the property.

Thanks in advance.

**Comment by Kobee1203** [comment]
There is no specific annotation to do this at the moment.

But a workaround is to use the Jackson `@JsonProperty` annotation on the field.

```
public interface MyDataset extends Dataset {

    MyDataset getProvWasDerivedFrom();

    void setProvWasDerivedFrom(MyDataset provWasDerivedFrom);
}

@JsonLdTypeName("MyDataset")
public class MyDatasetImpl extends DatasetImpl implements MyDataset {

    @JsonProperty("prov:wasDerivedFrom")
    private MyDataset provWasDerivedFrom;

    public MyDataset getProvWasDerivedFrom() {
        return provWasDerivedFrom;
    }

    public void setProvWasDerivedFrom(MyDataset provWasDerivedFrom) {
        this.provWasDerivedFrom = provWasDerivedFrom;
    }
}

public void serialize() throws JsonLdException {
    final JsonLdSerializer jsonLdSerializer = new JsonLdSerializerImpl(JsonLdSerializerOptions.builder().prettyPrint(true).build());

    MyDatasetImpl provWasDerivedFrom = new MyDatasetImpl();
    provWasDerivedFrom.addName(Text.of("MyName"));

    MyDataset myDataset = new MyDatasetImpl();
    myDataset.setProvWasDerivedFrom(provWasDerivedFrom);

    String result = jsonLdSerializer.serialize(myDataset);

    System.out.println(result);
}

```
will result in

```
{
  "@context" : "https://schema.org",
  "@type" : "MyDataset",
  "prov:wasDerivedFrom" : {
    "@type" : "MyDataset",
    "name" : "MyName"
  }
}
```

Are you ok with this solution?

**Comment by mrtylmz** [comment]
I had to replace string object from provWasDerivedFrom to prov:WasDerivedFrom after serialization.

But yours suggestion is better. I am gonna use it. It works. Thank you again!.
